/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanagementsystem;

/**
 *
 * @author ali
 */
public class EmployeeOptions extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeOptions
     */
    public EmployeeOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        workHours = new javax.swing.JButton();
        viewTask = new javax.swing.JButton();
        viewPen = new javax.swing.JButton();
        checkTask = new javax.swing.JButton();
        vacation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employyees Options");
        setLocation(new java.awt.Point(300, 200));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setText("Employee Operations :- ");

        workHours.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        workHours.setText("View Working Hours Per Month");
        workHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workHoursActionPerformed(evt);
            }
        });

        viewTask.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        viewTask.setText("View Tasks");
        viewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTaskActionPerformed(evt);
            }
        });

        viewPen.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        viewPen.setText("View Penalties");
        viewPen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPenActionPerformed(evt);
            }
        });

        checkTask.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        checkTask.setText("Check Task");
        checkTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTaskActionPerformed(evt);
            }
        });

        vacation.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        vacation.setText("Request Vacation");
        vacation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkTask, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vacation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewPen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(workHours)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkTask)
                    .addComponent(viewPen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vacation)
                    .addComponent(viewTask))
                .addGap(26, 26, 26)
                .addComponent(workHours)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTaskActionPerformed

    private void checkTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTaskActionPerformed
        dispose();
        checkTask c = new checkTask();
        c.setVisible(true);
    }//GEN-LAST:event_checkTaskActionPerformed

    private void viewPenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPenActionPerformed
        // TODO add your handling code here:
        dispose();
        ViewPenalties v = new ViewPenalties();
        v.setVisible(true);
    }//GEN-LAST:event_viewPenActionPerformed

    private void vacationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacationActionPerformed
        // TODO add your handling code here:
        dispose();
        RequestVacation r = new RequestVacation();
        r.setVisible(true);
    }//GEN-LAST:event_vacationActionPerformed

    private void workHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workHoursActionPerformed
        // TODO add your handling code here:
        dispose();
        WorkingHoursOverMonth w = new WorkingHoursOverMonth();
        w.setVisible(true);
    }//GEN-LAST:event_workHoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton vacation;
    private javax.swing.JButton viewPen;
    private javax.swing.JButton viewTask;
    private javax.swing.JButton workHours;
    // End of variables declaration//GEN-END:variables
}
